### ISSUE TITLE
Incorrect Outlet calculation

### ISSUE THREAD

**Issue by rupole1185** [shor-ty/humidityRhoThermo#1]
I run a simulation with buoyantHumidityPimpleFoam and, with the same parameters, with buoyantPimpleFoam.

In the beginning I noticed that buoyantHumidityPimpleFoam was not able to converge with "high" Courant (10 or above). For this I limited the Courant to be just 2.

A comparison with buoyantPimpleFoam showed that the limitation was mainly due to an incorrect solution at the outlet. I didn't run the simulation for a very large time, but already after 0.5 of simulated time, the results at the outlet had two very different behaviour.

Files for the two cases can be taken from here: https://storage.googleapis.com/backup-history-cfs/HUMIDITY.tar.gz

**Comment by shor-ty** [comment]
I am going to investigate into that. Thanks for the test case.

**Comment by shor-ty** [comment]
This problem is actually related to the p_rgh boundary condition which is in both cases not correct - just check the p_rgh and p field for the case without humidity. This is a problem we have in FOAM. 

https://www.cfd-online.com/Forums/openfoam-pre-processing/209487-correct-boundary-conditions-p_rgh-special-vertical-patches.html#post711588

https://www.cfd-online.com/Forums/openfoam-solving/125718-buoyantsimplefoam-watertank-5.html#post807099

Hence, it is not related to the library itself. I tried to use the idea from Jost but the initialization is not working.

Close #1

**Comment by rupole1185** [comment]
Hi Tobias,

sorry for the question but I can't see the error by looking at p_rgh and p
fields for the case without humidity. I just apply prghPressure = 1bar at
the outlet for p_rgh and for p everything is calculated. Maybe it's my
fault, but so far I never had troubles with this configuration.

Ruggero

**Comment by shor-ty** [comment]
If you check the "no-humidity" calculation, you see that the values of p are not the same as in the surrounding (even worse for p_rgh). The humidity library is more sensitive to that value/misbehavior. If you apply prghPressure to be 1 bar, it is not a smooth way or in other words... the boundary values is not set totally right. The humidity library is more sensitive to the value of p. Maybe we could stabilize the calculation by applying a reference pressure such as the incompressiblePerfectGas assumption. However, then we will loose the pressure influence.

If you make the outlet patch horizontal, it should work better. I cannot investigate into your case as it is way to large for a fast analysis.

**Comment by rupole1185** [comment]
Ok. I'll re-run the case with horizontal outlets.

Thanks,

Ruggero

**Comment by shor-ty** [comment]
@rupole1185 , any news regarding this issue?

**Comment by rupole1185** [comment]
Hi Tobias,

no I didn't work on that anymore.

Ruggero
